[project]
name = "crosstown-traffic"
version = "0.4.4"
description = "Whatabout the wherabouts"
authors = [{ name = "Vaughn Woerpel", email = "vaughnwoerpel@gmail.com" }]
requires-python = "~=3.13"
readme = "README.md"
dependencies = [
    "fastapi[standard]",
    "discord-py",
    "coloredlogs",
    "requests",
]

[dependency-groups]
dev = [
  "ruff",
]
