[project]
name = "crosstown-traffic"
version = "0.4.1"
description = "Whatabout the wherabouts"
authors = [{ name = "Vaughn Woerpel", email = "vaughnwoerpel@gmail.com" }]
requires-python = "~=3.13"
readme = "README.md"
dependencies = [
    "fastapi[standard]>=0.115.7,<0.116",
    "discord-py>=2.4.0,<3",
    "coloredlogs>=15.0.1,<16",
    "requests>=2.32.3,<3",
]

[dependency-groups]
dev = [
  "ruff>=0.9.6,<0.10",
]
