{{ if .Values.gateway }}
apiVersion: v1
kind: Service
metadata:
  name: traffic
spec:
  selector:
    app: {{ lower .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.gateway.containerPort }}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-cloudflare
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: traffic.vaughn.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traffic
            port:
              number: 80
{{ end }}