name: CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit


  docker-image:
    uses: ./.github/workflows/docker-image.yml
    needs:
      - build-and-test
    secrets: inherit