name: Code Quality & Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    name: "Code Quality"
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: "actions/checkout@v4"

    - name: Install Ruff
      uses: "astral-sh/ruff-action@v3"

    - name: Code Format
      run: "ruff format"

    - name: Linting
      run: "ruff check ."

