name: Code Quality & Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    name: "Code Quality"
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruff
      uses: astral-sh/ruff-action@v3

    - name: Code Format
      run: "ruff format"

    - name: Linting
      run: "ruff check"

      # Don't run these next steps if it's not a PR build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
      with:
        push: false